# Generated by Django 5.2.13 on 2026-04-07 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=30)),
                ('house_address', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('One-time', 'One-time'), ('Monthly Subscription', 'Monthly Subscription')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biller_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=80)),
                ('account_name', models.CharField(max_length=150)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_date', models.CharField(choices=[('Every 1st', 'Every 1st'), ('Every 5th', 'Every 5th'), ('Every 10th', 'Every 10th'), ('Every 15th', 'Every 15th'), ('Every 20th', 'Every 20th'), ('Every 25th', 'Every 25th'), ('Every 30th', 'Every 30th')], max_length=32)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billers', to='subscriptions.subscription')),
            ],
        ),
    ]
